#+INCLUDE: "./headers.org" :minlevel 1

#+AUTHOR:   Your name Here
#+TITLE:    Your Position or Tagline Here

#+PHOTO:    assets/photo.png

#+email:    your_name@email.com
#+MOBILE:   000-00-0000
#+ADDRESS:  Address Street
#+ADDRESS:  00000 Country
#+HOMEPAGE: www.homepage.com
#+GITHUB:   your_id
#+GITLAB:   your_id
#+LINKEDIN: your_id

#+BEGIN_EXPORT latex
\marginpar{
#+END_EXPORT

* My Life Philosophy

#+BEGIN_QUOTE
"Something smart or heartfelt, preferably in one sentence."
#+END_QUOTE

* Most Proud of

#+BEGIN_EXPORT latex
\cvachievement{\faTrophy}{Fantastic Achievement}{and some details about it}
\divider

\cvachievement{\faHeartbeat}{Another achievement}{more details about it of course}
\divider

\cvachievement{\faHeartbeat}{Another achievement}{more details about it of course}
#+END_EXPORT

* Strengths

#+BEGIN_EXPORT latex
\cvtag{Hard-working}
\cvtag{Eye for detail}\\
\cvtag{Motivator \& Leader}

\divider

\cvtag{C++}
\cvtag{Embedded Systems}\\
\cvtag{Statistical Analysis}
#+END_EXPORT

* Languages

#+BEGIN_EXPORT latex
\cvskill{English}{5}
\divider

\cvskill{Spanish}{4}
\divider

%% Supports X.5 values.
\cvskill{German}{3.5}
#+END_EXPORT

* Education

** Ph.D.\ in Your Discipline
:PROPERTIES:
:CV_ENV:   cventry
:FROM:     <2013-12-30 lun.>
:TO:       <2017-03-03 ven.>
:EMPLOYER: Your University
:END:

** M.Sc.\ in Your Discipline
:PROPERTIES:
:CV_ENV:   cventry
:FROM:     <2012-08-31 ven.>
:TO:       <2014-06-27 ven.>
:EMPLOYER: Your University
:END:

** B.Sc.\ in Your Discipline
:PROPERTIES:
:CV_ENV:   cventry
:FROM:     <2009-08-31 lun.>
:TO:       <2012-06-29 ven.>
:EMPLOYER: Your University
:END:


#+BEGIN_EXPORT latex
}
#+END_EXPORT

* Exprience

** Job Title 1
:PROPERTIES:
:CV_ENV:   cventry
:FROM:     <2015-03-02 lun.>
:TO:       Now
:LOCATION: Location 1
:EMPLOYER: Employer 1
:END:

- Job descrition 1
- Job descrition 2

** Job Title 2
:PROPERTIES:
:CV_ENV:   cventry
:FROM:     <2013-03-01 ven.>
:TO:       <2015-02-27 ven.>
:LOCATION: Location 2
:EMPLOYER: Employer 2
:END:

- Job descrition 1
- Job descrition 2

* Projects

** Project 1
:PROPERTIES:
:CV_ENV:   cventry
:FROM:     <2013-01-07 lun.>
:TO:       <2013-02-25 lun.>
:EMPLOYER: Funding agency/institution
:END:

- Detail

** Project 2
:PROPERTIES:
:CV_ENV:   cventry
:FROM:     <2012-10-08 lun.>
:TO:       <2012-12-21 ven.>
:EMPLOYER: Funding agency/institution
:END:

A short abstract would also work.

* A day of my life

#+BEGIN_EXPORT latex
% Adapted from @Jake's answer from http://tex.stackexchange.com/a/82729/226
% \wheelchart{outer radius}{inner radius}{
% comma-separated list of value/text width/color/detail}
\wheelchart{1.5cm}{0.5cm}{%
  6/8em/accent!30/{Sleep,\\beautiful sleep},
  3/8em/accent!40/Hopeful novelist by night,
  8/8em/accent!60/Daytime job,
  2/10em/accent/Sports and relaxation,
  5/6em/accent!20/Spending time with family
}
#+END_EXPORT


#+LATEX: \newpage
#+BEGIN_EXPORT latex
\marginpar{
#+END_EXPORT

* Referees

#+BEGIN_EXPORT latex
% \cvref{name}{email}{mailing address}
\cvref{Prof.\ Alpha Beta}{Institute}{a.beta@university.edu}
{Address Line 1\\Address line 2}

\divider

\cvref{Prof.\ Gamma Delta}{Institute}{g.delta@university.edu}
{Address Line 1\\Address line 2}
#+END_EXPORT

#+BEGIN_EXPORT latex
}
#+END_EXPORT

* Publications

** \faBook Books

- Conway D. (2000), Object Oriented Perl: /A comprehensive guide to concepts and
  programming techniques/. Connecticut, USA: Manning Publications Co.


#+BEGIN_EXPORT latex
\divider
#+END_EXPORT

** \faFile Journal Articles

- Codish M. and Marriott K. and Taboch C.K.. (2000), Improving program analyses
  by structure untupling. /Journal of Logic Programming, 43/ 251--263.
- Meyer B. (2000), A constraint-based framework for diagrammatic reasoning.
  /Applied Artificial Intelligence, 14/ 327--344.


#+BEGIN_EXPORT latex
\divider
#+END_EXPORT

** \faUsers Conference Proceedings



- Zou, W. Y., Socher, R., Cer, D. M., & Manning, C. D. (2013). Bilingual word
  embeddings for phrase-based machine translation. In
  /Emnlp/ (pp. 1393–1398).
- Hu, J., Wu, H., Jennings, A., & Wang, X. (2000). Fast and robust equalization:
  A case study. In /Proceedings of the world multiconference on systemics,
  cybernetics and informatics, (sci 2000), ﬂorida, usa, 23-26 july 2000/ (pp.
  398–403). FL, USA: International Institute of Informatics and Systemics.

* Org-mode file config :noexport:

# Local Variables:
# org-confirm-babel-evaluate: nil
# eval: (add-hook 'before-save-hook (lambda () (org-babel-ref-resolve "onsaveblock")) nil t)
# End:

#+NAME: onsaveblock
#+BEGIN_SRC emacs-lisp :exports none :result none :exec always
(require 'ox-extra)
(ox-extras-activate '(ignore-headlines))

(add-to-list 'load-path (concat "org-cv"))
(require 'ox-altacv)

(setq org-export-with-section-numbers nil)

(make-directory "build/" t)
(delete-file "build/pdfa.xmpi")
(delete-file "build/resume-altacv.pdf")
(delete-file "build/resume-altacv.tex")
(org-export-to-file 'altacv "build/resume-altacv.tex")
(org-latex-compile "build/resume-altacv.tex")

(make-directory "output/" t)
(delete-file "output/resume.pdf")
(copy-file "build/resume-altacv.pdf" "output/resume.pdf" t)
#+END_SRC
